export const FETCH_CURR_LIST_REQUEST = 'FETCH_CURR_LIST_REQUEST';
export const FETCH_CURR_LIST_SUCCESS = 'FETCH_CURR_LIST_SUCCESS';
export const FETCH_CURR_LIST_ERROR = 'FETCH_CURR_LIST_ERROR';

export const ADD_TO_FAVORITE_CURR_LIST = 'ADD_TO_FAVORITE_CURR_LIST';
export const REMOVE_FROM_FAVORITE_CURR_LIST = 'REMOVE_FROM_FAVORITE_CURR_LIST';

export const CONVERT_CURRENCY_REQUEST = 'CONVERT_CURRENCY_REQUEST';
export const CONVERT_CURRENCY_SUCCESS = 'CONVERT_CURRENCY_SUCCESS';
export const CONVERT_CURRENCY_ERROR = 'CONVERT_CURRENCY_ERROR';